name: Test Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  test-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Create .env file
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          STACK_NAME: ${{ secrets.STACK_NAME }}
          FRONTEND_HOST: ${{ secrets.FRONTEND_HOST }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          BACKEND_CORS_ORIGINS: ${{ secrets.BACKEND_CORS_ORIGINS }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
          FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DOCKER_IMAGE_BACKEND: ${{ secrets.DOCKER_IMAGE_BACKEND }}
          DOCKER_IMAGE_FRONTEND: ${{ secrets.DOCKER_IMAGE_FRONTEND }}
        run: |
          env | grep -E '^(DOMAIN|STACK_NAME|FRONTEND_HOST|ENVIRONMENT|BACKEND_CORS_ORIGINS|SECRET_KEY|FIRST_SUPERUSER|FIRST_SUPERUSER_PASSWORD|PROJECT_NAME|POSTGRES_SERVER|POSTGRES_PORT|POSTGRES_DB|POSTGRES_USER|POSTGRES_PASSWORD|DOCKER_IMAGE_BACKEND|DOCKER_IMAGE_FRONTEND)=' > .env
          echo "SMTP_HOST=" >> .env
          echo "SMTP_USER=" >> .env
          echo "SMTP_PASSWORD=" >> .env
          echo "EMAILS_FROM_EMAIL=info@example.com" >> .env
          echo "SENTRY_DSN=" >> .env
      - run: docker compose build backend frontend
      - run: docker compose down -v --remove-orphans
      - run: docker compose up -d --wait backend frontend adminer
      - name: Test backend is up
        run: curl http://localhost:8000/api/v1/utils/health-check
      - name: Test frontend is up
        run: curl http://localhost:5173
      - run: docker compose down -v --remove-orphans
